### PR TITLE
Include changes on master into flyway branch

### PR DESCRIPTION
**Pull request by peterdesmet**

### CODE REVIEW

**Comment by peterdesmet** [comment]
Just to make sure I'm not doing anything stupid... @CeciliaNilsson709, you have never committed the generated .html in docs to the flyway branch, correct?

**Comment by CeciliaNilsson709** [comment]
No, don't think I have...

**Comment by peterdesmet** [comment]
Ok, I merged. Best to `Fetch Origin/Pull origin` in GitHub Desktop on your computer. I hope that goes well. 😅

**Comment by CeciliaNilsson709** [comment]
Seems to have worked fine 🙌 🙏

**Pull request merged**
